import { categories, getCategoryBySlug } from "./categories";
import { premiumImages } from "./premiumImages";

export type Availability = "In Stock" | "Made to Order" | "Out of Stock" | "Unavailable";
export type ProductStatus = "active" | "draft" | "archived";

export type Product = {
  id: string;
  slug: string;
  name: string;
  categorySlug: string;
  categoryName: string;
  shortDescription: string;
  description: string;
  material: string;
  sizes: string[];
  weight?: string;
  colors: string[];
  retailPrice: string;
  bulkPrice?: string;
  moq?: string;
  leadTime?: string;
  availability: Availability;
  quoteOnly?: boolean;
  image: string;
  gallery?: string[];
  featured?: boolean;
  status: ProductStatus;
  adminNotes?: string;
  sku?: string;
  dimensions?: string;
  careInstructions?: string;
  origin?: string;
  tags?: string[];
  updatedAt?: string;

  // Compatibility fields for current showroom/detail UI. Remove after UI migration.
  category: string;
  summary: string;
  handmadeNote: string;
  suggestedUse: string;
  customizationOptions: string;
  customNote: string;
  imageSrc?: string;
};

type ProductInput = Omit<
  Product,
  "category" | "summary" | "handmadeNote" | "suggestedUse" | "customizationOptions" | "customNote" | "imageSrc"
> & {
  handmadeNote?: string;
  suggestedUse?: string;
  customizationOptions?: string;
  customNote?: string;
};

function createProduct(input: ProductInput): Product {
  return {
    ...input,
    category: input.categoryName,
    summary: input.shortDescription,
    handmadeNote:
      input.handmadeNote ??
      "Each piece is shaped and finished by hand, so subtle surface and color variations are part of the handmade character.",
    suggestedUse:
      input.suggestedUse ??
      "Designed for boutiques, interior designers, hospitality buyers, gift assortments, and custom wholesale programs.",
    customizationOptions:
      input.customizationOptions ??
      "Custom colors, sizing, labeling, packaging direction, and repeatable assortment planning can be discussed for trade orders.",
    customNote:
      input.customNote ??
      "Available for wholesale discussion, custom sampling, and buyer-led development.",
    imageSrc: input.image,
    sku: input.sku ?? input.id.toUpperCase().replace("PROD-", "HH-"),
    origin: input.origin ?? "Handmade in Nepal",
    tags: input.tags ?? [input.categorySlug, input.availability.toLowerCase().replaceAll(" ", "-")],
    updatedAt: input.updatedAt ?? "2026-05-15",
  };
}

export const products: Product[] = [
  createProduct({
    id: "prod-rug-soft-architecture",
    slug: "soft-architecture-felt-rug",
    name: "Soft Architecture Felt Rug",
    categorySlug: "rugs",
    categoryName: "Rugs",
    shortDescription: "A dense handmade felt rug with quiet structure for refined living and hospitality spaces.",
    description: "A premium felt rug designed around soft geometry, wool density, and calm interior use. Suitable for residential, boutique, and hospitality programs.",
    material: "100% New Zealand wool felt, natural soap, water, hand finishing",
    sizes: ["120 x 180 cm", "160 x 240 cm", "200 x 300 cm", "Custom"],
    weight: "Approx. 5-16 kg depending on size",
    colors: ["Ivory", "Warm Grey", "Walnut", "Custom"],
    retailPrice: "$420",
    bulkPrice: "Trade pricing available",
    moq: "5 pieces",
    leadTime: "4-8 weeks",
    availability: "In Stock",
    image: premiumImages.categories.rugs,
    gallery: [premiumImages.categories.rugs, premiumImages.showroom.rugDisplay],
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-rug-felt-ball",
    slug: "himalayan-felt-ball-rug",
    name: "Himalayan Felt Ball Rug",
    categorySlug: "rugs",
    categoryName: "Rugs",
    shortDescription: "Hand-rolled wool felt balls arranged into a tactile graphic floor surface.",
    description: "A felt ball rug concept with strong texture, modular color planning, and practical wholesale customization for retail and interior buyers.",
    material: "Hand-rolled New Zealand wool felt balls with stitched backing",
    sizes: ["90 cm round", "120 cm round", "140 cm round", "Custom"],
    weight: "Approx. 4-11 kg depending on size",
    colors: ["Natural Mix", "Earth Mix", "Bright Mix", "Custom"],
    retailPrice: "$360",
    bulkPrice: "Trade pricing available",
    moq: "6 pieces",
    leadTime: "4-7 weeks",
    availability: "Out of Stock",
    image: premiumImages.showroom.rugDisplay,
    gallery: [premiumImages.showroom.rugDisplay, premiumImages.categories.rugs],
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-rug-runner",
    slug: "wool-felt-runner",
    name: "Wool Felt Runner",
    categorySlug: "rugs",
    categoryName: "Rugs",
    shortDescription: "A narrow felt runner for hallways, bedside styling, and boutique interior programs.",
    description: "A practical runner format made for hospitality corridors, retail styling, and custom interior projects that need warmth without visual heaviness.",
    material: "New Zealand wool felt with hand-finished edges",
    sizes: ["70 x 200 cm", "80 x 240 cm", "90 x 300 cm", "Custom"],
    weight: "Approx. 3-10 kg depending on size",
    colors: ["Oat", "Charcoal", "Olive", "Custom"],
    retailPrice: "$280",
    bulkPrice: "Trade pricing available",
    moq: "8 pieces",
    leadTime: "4-8 weeks",
    availability: "Unavailable",
    image: premiumImages.showroom.whiteCarpetTexture,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-throw-winter-layer",
    slug: "winter-layer-wool-throw",
    name: "Winter Layer Wool Throw",
    categorySlug: "blankets-throws",
    categoryName: "Blankets & Throws",
    shortDescription: "A soft wool throw designed for sofas, beds, gifting, and seasonal retail stories.",
    description: "A warm layering textile for interiors and gift assortments, developed with calm color options and soft handmade texture.",
    material: "100% New Zealand wool",
    sizes: ["100 x 150 cm", "130 x 180 cm", "Custom"],
    weight: "Approx. 1.2-2.4 kg",
    colors: ["Ivory", "Mushroom", "Clay", "Custom"],
    retailPrice: "$145",
    bulkPrice: "$96+ by volume",
    moq: "12 pieces",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.categories.blanketsThrows,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-throw-textured-sofa",
    slug: "textured-sofa-throw",
    name: "Textured Sofa Throw",
    categorySlug: "blankets-throws",
    categoryName: "Blankets & Throws",
    shortDescription: "A tactile wool throw for living rooms, boutique displays, and hospitality suites.",
    description: "A refined textile layer with a soft hand-feel and simple palette planning for interior and retail programs.",
    material: "New Zealand wool with felted texture",
    sizes: ["120 x 160 cm", "140 x 200 cm", "Custom"],
    weight: "Approx. 1.4-2.8 kg",
    colors: ["Natural", "Grey", "Blush", "Custom"],
    retailPrice: "$168",
    bulkPrice: "$112+ by volume",
    moq: "12 pieces",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.lookbook.cozyHomeTextile,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-throw-custom-palette",
    slug: "custom-palette-blanket-program",
    name: "Custom Palette Blanket Program",
    categorySlug: "blankets-throws",
    categoryName: "Blankets & Throws",
    shortDescription: "Buyer-led throw and blanket colors for seasonal, hospitality, or private-label programs.",
    description: "A custom blanket development option for buyers who need coordinated palettes, repeatable sizing, and collection-level planning.",
    material: "New Zealand wool, project-specific finishing",
    sizes: ["Sample size", "Standard throw", "Custom"],
    colors: ["Buyer palette", "Seasonal palette", "Private-label palette"],
    retailPrice: "Ask for Quote",
    bulkPrice: "Project pricing",
    moq: "25 pieces",
    leadTime: "Sample: 3-4 weeks; production: 6-10 weeks",
    availability: "Made to Order",
    quoteOnly: true,
    image: premiumImages.lookbook.colorStoryYarn,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-wall-himalayan-texture",
    slug: "himalayan-texture-wall-hanging",
    name: "Himalayan Texture Wall Hanging",
    categorySlug: "wall-hangings",
    categoryName: "Wall Hangings",
    shortDescription: "A soft textile wall piece with handmade felt texture and calm interior presence.",
    description: "A textile-led wall hanging for homes, boutiques, hospitality rooms, and display-focused interiors that need warmth and tactility.",
    material: "New Zealand wool felt with hand-shaped surface detail",
    sizes: ["60 x 90 cm", "90 x 120 cm", "Custom"],
    weight: "Approx. 1-3 kg",
    colors: ["Ivory", "Sand", "Walnut", "Custom"],
    retailPrice: "$210",
    bulkPrice: "$148+ by volume",
    moq: "8 pieces",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.categories.wallHangings,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-wall-abstract-panel",
    slug: "abstract-felt-wall-panel",
    name: "Abstract Felt Wall Panel",
    categorySlug: "wall-hangings",
    categoryName: "Wall Hangings",
    shortDescription: "A modern felt panel for hospitality, boutique, and interior design projects.",
    description: "A customizable wall panel direction using felt surface, color blocking, and hand-finished dimensional detail.",
    material: "Wool felt with textile backing",
    sizes: ["70 x 100 cm", "100 x 140 cm", "Custom"],
    weight: "Approx. 1.5-4 kg",
    colors: ["Neutral", "Earth", "Custom"],
    retailPrice: "$260",
    bulkPrice: "Trade pricing available",
    moq: "6 pieces",
    leadTime: "5-9 weeks",
    availability: "Made to Order",
    image: premiumImages.textileVariety,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-wall-color-story",
    slug: "color-story-wall-hanging",
    name: "Color Story Wall Hanging",
    categorySlug: "wall-hangings",
    categoryName: "Wall Hangings",
    shortDescription: "A palette-led wall piece for visual merchandising and custom interior stories.",
    description: "A color-driven wall textile that can be developed around buyer palettes, seasonal assortments, or hospitality schemes.",
    material: "New Zealand wool felt, hand-shaped color elements",
    sizes: ["50 x 70 cm", "80 x 110 cm", "Custom"],
    colors: ["Pastel", "Earth", "Buyer palette"],
    retailPrice: "$190",
    bulkPrice: "$132+ by volume",
    moq: "10 pieces",
    leadTime: "4-8 weeks",
    availability: "Made to Order",
    image: premiumImages.lookbook.colorStoryYarn,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-decor-nest-basket",
    slug: "nest-felt-storage-basket",
    name: "Nest Felt Storage Basket",
    categorySlug: "home-decorations",
    categoryName: "Home Decorations",
    shortDescription: "A soft sculptural felt basket for home storage, display, and gifting.",
    description: "A handmade storage basket with tactile wool structure, useful for retail displays, home styling, and seasonal assortments.",
    material: "Wool felt with hand-shaped form",
    sizes: ["Small", "Medium", "Large", "Nested set"],
    weight: "Approx. 0.4-1.4 kg",
    colors: ["Natural", "Charcoal", "Clay", "Custom"],
    retailPrice: "$68",
    bulkPrice: "$42+ by volume",
    moq: "24 pieces",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.categories.homeDecorations,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-decor-wool-garland",
    slug: "artisan-wool-garland",
    name: "Artisan Wool Garland",
    categorySlug: "home-decorations",
    categoryName: "Home Decorations",
    shortDescription: "A handmade felt garland for seasonal displays, boutiques, and home accents.",
    description: "A flexible decor piece for windows, retail merchandising, gifting assortments, and holiday or seasonal collection planning.",
    material: "Wool felt balls and hand-strung cotton cord",
    sizes: ["150 cm", "200 cm", "Custom"],
    colors: ["Natural", "Holiday", "Pastel", "Custom"],
    retailPrice: "$34",
    bulkPrice: "$21+ by volume",
    moq: "50 pieces",
    leadTime: "3-5 weeks",
    availability: "Made to Order",
    image: premiumImages.hero.feature,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-decor-table-accent",
    slug: "felt-table-accent-set",
    name: "Felt Table Accent Set",
    categorySlug: "home-decorations",
    categoryName: "Home Decorations",
    shortDescription: "A refined set of felt coasters, trivets, or table objects for everyday styling.",
    description: "A practical decor assortment for homeware buyers, boutique gifting, hospitality rooms, and private-label table stories.",
    material: "Dense wool felt with hand-cut and hand-finished details",
    sizes: ["Coaster set", "Trivet set", "Mixed set"],
    colors: ["Ivory", "Olive", "Walnut", "Custom"],
    retailPrice: "$46",
    bulkPrice: "$29+ by volume",
    moq: "36 sets",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.sustainability.woolTexture,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-toy-forest-animal",
    slug: "forest-animal-felt-set",
    name: "Forest Animal Felt Set",
    categorySlug: "toys",
    categoryName: "Toys",
    shortDescription: "A soft handmade animal set for boutique gifting and nursery displays.",
    description: "A playful wool felt toy assortment shaped by hand for gift stores, museum shops, nursery stories, and family-focused boutiques.",
    material: "Wool felt, cotton stitching, soft filling where required",
    sizes: ["Set of 3", "Set of 5", "Custom assortment"],
    colors: ["Forest", "Neutral", "Custom"],
    retailPrice: "$58",
    bulkPrice: "$38+ by volume",
    moq: "30 sets",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.categories.toys,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-toy-felt-doll",
    slug: "soft-felt-doll-set",
    name: "Soft Felt Doll Set",
    categorySlug: "toys",
    categoryName: "Toys",
    shortDescription: "Handmade felt dolls for curated toy, gift, and family retail collections.",
    description: "A soft doll assortment with handmade character, gentle colors, and buyer-led customization options.",
    material: "Wool felt, cotton stitching, soft filling",
    sizes: ["Small", "Medium", "Assorted set"],
    colors: ["Soft Brights", "Pastel", "Custom"],
    retailPrice: "$42",
    bulkPrice: "$27+ by volume",
    moq: "40 pieces",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.showroom.feltDolls,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-toy-nursery-mobile",
    slug: "nursery-felt-mobile",
    name: "Nursery Felt Mobile",
    categorySlug: "toys",
    categoryName: "Toys",
    shortDescription: "A soft hanging felt mobile for nursery, gifting, and family retail stories.",
    description: "A gentle decorative toy concept for nurseries and boutiques, with custom motif and palette options for wholesale buyers.",
    material: "Wool felt, cotton thread, lightweight hanging structure",
    sizes: ["Standard", "Custom"],
    colors: ["Cloud", "Forest", "Custom"],
    retailPrice: "$64",
    bulkPrice: "$42+ by volume",
    moq: "24 pieces",
    leadTime: "4-8 weeks",
    availability: "Made to Order",
    image: premiumImages.owlToys,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-accessory-felt-slippers",
    slug: "handmade-felt-slippers",
    name: "Handmade Felt Slippers",
    categorySlug: "personal-accessories",
    categoryName: "Personal Accessories",
    shortDescription: "Warm wool felt slippers for lifestyle stores, gifting, and hospitality programs.",
    description: "A wearable felt product with soft structure and practical sizing for retail and private-label buyer programs.",
    material: "Wool felt with optional sole finish",
    sizes: ["S", "M", "L", "XL", "Custom size run"],
    colors: ["Natural", "Grey", "Walnut", "Custom"],
    retailPrice: "$72",
    bulkPrice: "$48+ by volume",
    moq: "36 pairs",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.categories.personalAccessories,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-accessory-coin-purse",
    slug: "felt-coin-purse",
    name: "Felt Coin Purse",
    categorySlug: "personal-accessories",
    categoryName: "Personal Accessories",
    shortDescription: "A small handmade wool accessory for gifting, museum shops, and lifestyle retail.",
    description: "A compact felt purse that can be developed in custom colors, motifs, zipper directions, and private-label packaging.",
    material: "Wool felt with zipper or button closure",
    sizes: ["Small", "Medium", "Custom"],
    colors: ["Bright Mix", "Neutral", "Custom"],
    retailPrice: "$24",
    bulkPrice: "$15+ by volume",
    moq: "80 pieces",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.knittedStack,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-accessory-wool-mittens",
    slug: "handmade-wool-mittens",
    name: "Handmade Wool Mittens",
    categorySlug: "personal-accessories",
    categoryName: "Personal Accessories",
    shortDescription: "Soft wool mittens for winter gifting, boutique lifestyle ranges, and seasonal programs.",
    description: "A cold-weather accessory option for seasonal assortments with buyer-led colors, sizing, and packaging direction.",
    material: "Wool felt and stitched finishing",
    sizes: ["S", "M", "L", "Custom"],
    colors: ["Winter White", "Blue", "Grey", "Custom"],
    retailPrice: "$38",
    bulkPrice: "$25+ by volume",
    moq: "60 pairs",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.mittenCup,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-pet-cave",
    slug: "cozy-felt-pet-cave",
    name: "Cozy Felt Pet Cave",
    categorySlug: "pet-accessories",
    categoryName: "Pet Accessories",
    shortDescription: "A warm handmade felt cave for pet boutiques and design-conscious homes.",
    description: "A sculptural pet cave concept made with dense wool felt for comfort-led retail and lifestyle assortments.",
    material: "Durable wool felt with hand-shaped form",
    sizes: ["Small", "Medium", "Large", "Custom"],
    weight: "Approx. 1.2-3.8 kg",
    colors: ["Natural", "Charcoal", "Taupe", "Custom"],
    retailPrice: "$128",
    bulkPrice: "$86+ by volume",
    moq: "12 pieces",
    leadTime: "5-9 weeks",
    availability: "Made to Order",
    image: premiumImages.sustainability.naturalWool,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-pet-mat",
    slug: "signature-felt-pet-mat",
    name: "Signature Felt Pet Mat",
    categorySlug: "pet-accessories",
    categoryName: "Pet Accessories",
    shortDescription: "A dense wool felt mat for pet comfort, boutique retail, and refined interiors.",
    description: "A flat felt pet accessory designed for easy retail placement, neutral palettes, and custom size grading.",
    material: "Dense New Zealand wool felt",
    sizes: ["45 x 60 cm", "60 x 80 cm", "Custom"],
    weight: "Approx. 0.8-2.4 kg",
    colors: ["Oat", "Grey", "Walnut", "Custom"],
    retailPrice: "$74",
    bulkPrice: "$49+ by volume",
    moq: "24 pieces",
    leadTime: "4-7 weeks",
    availability: "Made to Order",
    image: premiumImages.showroom.whiteCarpetTexture,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-pet-toy-set",
    slug: "wool-pet-toy-set",
    name: "Wool Pet Toy Set",
    categorySlug: "pet-accessories",
    categoryName: "Pet Accessories",
    shortDescription: "A felt toy set for pet-focused gifting and lifestyle retail assortments.",
    description: "A playful pet accessory concept with simple forms, felt density, and buyer-led color options.",
    material: "Wool felt with hand stitching",
    sizes: ["Set of 3", "Set of 5", "Custom assortment"],
    colors: ["Natural", "Bright", "Custom"],
    retailPrice: "$32",
    bulkPrice: "$20+ by volume",
    moq: "50 sets",
    leadTime: "3-6 weeks",
    availability: "Made to Order",
    image: premiumImages.hero.feature,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-custom-buyer-pack",
    slug: "custom-buyer-development-pack",
    name: "Custom Buyer Development Pack",
    categorySlug: "custom-designs",
    categoryName: "Custom Designs",
    shortDescription: "A guided sample development program for buyer-led felt and wool collections.",
    description: "A structured custom development path for buyers who need new forms, sizes, colors, and product families before production.",
    material: "Project-specific wool felt and handcraft techniques",
    sizes: ["Sample set", "Production size run", "Custom"],
    colors: ["Buyer palette", "Private-label palette"],
    retailPrice: "Ask for Quote",
    bulkPrice: "Project pricing",
    moq: "Project-based",
    leadTime: "Sample: 3-5 weeks; production: quoted",
    availability: "Made to Order",
    quoteOnly: true,
    image: premiumImages.categories.customDesigns,
    featured: true,
    status: "active",
  }),
  createProduct({
    id: "prod-custom-hospitality-rug",
    slug: "hospitality-rug-program",
    name: "Hospitality Rug Program",
    categorySlug: "custom-designs",
    categoryName: "Custom Designs",
    shortDescription: "Custom felt rug development for hotels, suites, studios, and interior buyers.",
    description: "A project-based rug program for dimensions, palettes, density, border direction, and repeatable hospitality production.",
    material: "New Zealand wool felt, project-specific construction",
    sizes: ["Room size", "Runner", "Custom"],
    colors: ["Project palette"],
    retailPrice: "Ask for Quote",
    bulkPrice: "Project pricing",
    moq: "Project-based",
    leadTime: "Quoted by scope",
    availability: "Made to Order",
    quoteOnly: true,
    image: premiumImages.showroom.rugDisplay,
    featured: false,
    status: "active",
  }),
  createProduct({
    id: "prod-custom-private-label",
    slug: "private-label-felt-product-line",
    name: "Private Label Felt Product Line",
    categorySlug: "custom-designs",
    categoryName: "Custom Designs",
    shortDescription: "Private-label felt product planning for boutiques, ethical importers, and retail partners.",
    description: "A custom assortment program covering forms, material direction, labeling, packaging, color systems, and repeat order planning.",
    material: "Project-specific wool felt and mixed handcraft techniques",
    sizes: ["Assortment-based", "Custom"],
    colors: ["Buyer palette", "Seasonal palette", "Custom"],
    retailPrice: "Ask for Quote",
    bulkPrice: "Project pricing",
    moq: "Project-based",
    leadTime: "Quoted by scope",
    availability: "Made to Order",
    quoteOnly: true,
    image: premiumImages.trade.weavingLoomDetail,
    featured: false,
    status: "active",
  }),
];

export function getActiveProducts() {
  return products.filter((product) => product.status === "active");
}

export function getFeaturedProducts() {
  return getActiveProducts().filter((product) => product.featured);
}

export function getProductsByCategory(categorySlug: string) {
  return getActiveProducts().filter((product) => product.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProduct(slug: string) {
  return getProductBySlug(slug);
}

export { categories, getCategoryBySlug };
